# Generated by Django 5.2 on 2025-04-25 04:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('transporte', models.CharField(choices=[('aereo', 'Aéreo'), ('maritimo', 'Marítimo')], default='aereo', max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='destinos/')),
                ('precio_general', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_vip', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_base_envio', models.DecimalField(decimal_places=2, default=10, help_text='Precio base para envío de paquetes a este destino', max_digits=10)),
                ('precio_por_kilo_extra', models.DecimalField(decimal_places=2, default=2, help_text='Precio por cada kilo adicional después del peso base', max_digits=10)),
                ('peso_base', models.DecimalField(decimal_places=2, default=10, help_text='Peso base en kg para el cálculo del envío', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('aspirante', 'Aspirante'), ('empleado', 'Empleado'), ('admin', 'Administrador')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('vip', 'VIP')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('carrito', 'En carrito'), ('vendido', 'Vendido')], default='libre', max_length=20)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos', to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='users.destino')),
            ],
        ),
        migrations.CreateModel(
            name='CosteEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_adicional', models.DecimalField(decimal_places=2, default=0, help_text='Costo adicional que se sumará al precio base del envío para este destino', max_digits=10)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional del costo adicional', max_length=255)),
                ('destino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coste_envio', to='users.destino')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='users.destino')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoBoletos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('boletos', models.ManyToManyField(blank=True, to='users.boleto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.destino')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.horario')),
            ],
        ),
        migrations.AddField(
            model_name='boleto',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='users.horario'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('pmovil', 'Pago Móvil')], default='pmovil', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia del pago móvil', max_length=100, null=True)),
                ('numero_tarjeta', models.CharField(blank=True, help_text='Campo sin uso para Pago Móvil', max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('electronica', 'Electrónica'), ('ropa', 'Ropa'), ('maquinaria', 'Maquinaria'), ('otros', 'Otros')], max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.TextField()),
                ('receptor', models.CharField(max_length=100)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('precio_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('carrito', 'En carrito'), ('vendido', 'Vendido')], default='carrito', max_length=10)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.destino')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoPaquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.destino')),
                ('paquetes', models.ManyToManyField(blank=True, to='users.paquete')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.destino')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.horario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boletos', models.ManyToManyField(blank=True, to='users.boleto')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.destino')),
                ('paquetes', models.ManyToManyField(blank=True, to='users.paquete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
